server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdb-4ghbgdie.cd.tencentcdb.com:10064/tensquare_recruit
    username: root
    password: Coweii123@
  jpa: 
    database: MySQL
    show-sql: true
