server:
  port: 9011
spring:
  application:
    name: tensquare-friend2 #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///tensquare_friend?serverTimezone=UTC
    username: root
    password: 7684
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
    instance:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true
jwt-config:
  key: Coweii123@
  ttl: 86400000  #有效时间, 1000*60*60*24
  issuer: Lin